import { useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence, useInView } from 'framer-motion'
import { FiArrowUpRight, FiMenu, FiX, FiPhone, FiMessageCircle, FiMapPin, FiInstagram, FiFacebook, FiLinkedin, FiChevronLeft, FiChevronRight, FiDownload } from 'react-icons/fi'
import { projectData as d } from './data/projectData'

const fade = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .7, ease: [.22, 1, .36, 1] } } }
const reveal = { initial: 'hidden', whileInView: 'show', viewport: { once: true, amount: .18 }, variants: fade }

function Navbar() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false)
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 40); window.addEventListener('scroll', fn); return () => window.removeEventListener('scroll', fn) }, [])
  const links = [['About', 'about'], ['Amenities', 'amenities'], ['Plans', 'plans'], ['Gallery', 'gallery'], ['Location', 'location']]
  return <header className={`nav ${scrolled ? 'nav--solid' : ''}`}><a href="#home" className="brand"><span className="brand-mark">R</span><span>{d.name}</span></a><nav className={open ? 'nav-links nav-links--open' : 'nav-links'}>{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href="#enquire" onClick={() => setOpen(false)}>Enquire <FiArrowUpRight /></a></nav><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <FiX /> : <FiMenu />}</button></header>
}
function Hero() { return <section className="hero" id="home"><div className="hero-image" style={{ backgroundImage: `url(${d.hero})` }} /><div className="hero-overlay" /><div className="hero-content"><motion.p {...reveal} className="eyebrow">{d.eyebrow} <span /></motion.p><motion.h1 {...reveal}>Your dream home<br /><em>starts here.</em></motion.h1><motion.p {...reveal} className="hero-sub">Premium 1, 2 & 3 BHK residences<br />shaped around light, landscape and long horizons.</motion.p><motion.div {...reveal} className="hero-actions"><a className="btn btn-light" href="#about">Explore project <FiArrowUpRight /></a><a className="btn btn-outline" href="#enquire">Enquire now <FiArrowUpRight /></a></motion.div><div className="hero-price"><small>Residences from</small><strong>₹ 78 Lakh<sup>*</sup></strong></div></div><a href="#about" className="scroll-cue"><span className="scroll-line" /> Scroll to discover</a></section> }
function About() { return <section className="section about" id="about"><motion.div {...reveal} className="about-copy"><p className="eyebrow dark">The Aurelia way <span /></p><h2>A home that gives<br /><em>life more room.</em></h2><p className="lead">Aurelia Heights is an invitation to live a little more deliberately. Set within a quiet, green pocket of Baner, every home is considered to bring you closer to the things that matter.</p><p>From the first light across your living room to the last conversation on the terrace, this is a place designed for the beautiful in-between moments.</p><a href="#enquire" className="text-link">Discover the story <FiArrowUpRight /></a></motion.div><motion.div {...reveal} className="about-image"><img src={d.aboutImage} alt="Warmly lit Aurelia Heights living room" /><span className="image-caption">A quiet corner, made yours</span></motion.div></section> }
function Highlights() { const ref = useRef(); const inView = useInView(ref, { once: true, amount: .4 }); return <section className="highlights" ref={ref}>{d.highlights.map((x, i) => <motion.div {...reveal} transition={{ delay: i * .1 }} className="highlight" key={x.label}><div className="highlight-value">{inView ? <Counter to={x.value} /> : '0'}<sup>{x.suffix}</sup></div><p>{x.label}</p></motion.div>)}</section> }
function Counter({ to }) { const [n, setN] = useState(0); useEffect(() => { let start = 0; const step = () => { start += Math.max(1, Math.round(to / 30)); if (start >= to) { setN(to); return } setN(start); requestAnimationFrame(step) }; requestAnimationFrame(step) }, [to]); return n }
function Amenities() { return <section className="section amenities" id="amenities"><motion.div {...reveal} className="section-head"><p className="eyebrow dark">The everyday, elevated <span /></p><h2>Made for your<br /><em>best days.</em></h2><p>Every detail has a purpose. Every space, an invitation.</p></motion.div><div className="amenity-grid">{d.amenities.map(([num, title, desc], i) => <motion.article {...reveal} transition={{ delay: i * .05 }} className="amenity" key={title}><span className="amenity-num">{num}</span><h3>{title}</h3><p>{desc}</p><FiArrowUpRight className="amenity-arrow" /></motion.article>)}</div></section> }
function Plans() { const [active, setActive] = useState(1); const plan = d.plans[active]; return <section className="section plans" id="plans"><div className="plans-heading"><motion.div {...reveal}><p className="eyebrow dark">Find your fit <span /></p><h2>Room to live<br /><em>your way.</em></h2></motion.div><div className="plan-tabs">{d.plans.map((p, i) => <button className={active === i ? 'active' : ''} key={p.label} onClick={() => setActive(i)}>{p.label}</button>)}</div></div><AnimatePresence mode="wait"><motion.div key={plan.label} className="plan-detail" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} transition={{ duration: .35 }}><div className="plan-image"><img src={plan.image} alt={`${plan.label} interior`} /><span>Indicative interior visual</span></div><div className="plan-info"><p className="plan-kicker">{plan.label} residence</p><h3>{plan.area}</h3><p>{plan.config}</p><div className="plan-price"><small>Starting at</small><strong>{plan.price}</strong></div><a href={d.brochure} download className="btn btn-dark">Download floor plan <FiDownload /></a></div></motion.div></AnimatePresence></section> }
function Gallery() { const [selected, setSelected] = useState(null); const next = () => setSelected((selected + 1) % d.gallery.length); const prev = () => setSelected((selected - 1 + d.gallery.length) % d.gallery.length); return <section className="section gallery" id="gallery"><motion.div {...reveal} className="section-head gallery-head"><div><p className="eyebrow dark">A glimpse within <span /></p><h2>See it. Feel it.<br /><em>Call it home.</em></h2></div><p>Spaces that photograph beautifully.<br />Spaces that live even better.</p></motion.div><div className="gallery-grid">{d.gallery.map((img, i) => <motion.button {...reveal} transition={{ delay: i * .06 }} className={`gallery-item gallery-item-${i + 1}`} key={img + i} onClick={() => setSelected(i)}><img src={img} alt={`Aurelia Heights gallery view ${i + 1}`} loading="lazy" /><span><FiArrowUpRight /></span></motion.button>)}</div>{selected !== null && <div className="lightbox" onClick={() => setSelected(null)}><button className="lightbox-close" onClick={() => setSelected(null)}><FiX /></button><button className="lightbox-prev" onClick={e => { e.stopPropagation(); prev() }}><FiChevronLeft /></button><img src={d.gallery[selected]} alt="Expanded gallery view" onClick={e => e.stopPropagation()} /><button className="lightbox-next" onClick={e => { e.stopPropagation(); next() }}><FiChevronRight /></button></div>}</section> }
function Location() { return <section className="location" id="location"><div className="location-copy"><motion.div {...reveal}><p className="eyebrow">Well connected, naturally <span /></p><h2>The city,<br /><em>within reach.</em></h2><p className="lead">A peaceful address with the best of Baner, Balewadi and Pune just minutes away.</p><div className="distance-list"><div><strong>07 min</strong><span>Baner High Street</span></div><div><strong>12 min</strong><span>Hinjewadi Phase 1</span></div><div><strong>18 min</strong><span>Pune University</span></div><div><strong>25 min</strong><span>Pune Airport</span></div></div><a className="btn btn-light" href="https://maps.google.com/?q=Baner,Pune" target="_blank" rel="noreferrer">Get directions <FiMapPin /></a></motion.div></div><div className="map"><iframe title="Aurelia Heights location map" src={d.mapUrl} loading="lazy" /></div></section> }
function Enquiry() { const [sent, setSent] = useState(false); const submit = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const msg = `Hi, I am interested in ${d.name}.%0AName: ${f.get('name')}%0AMobile: ${f.get('mobile')}%0AConfiguration: ${f.get('configuration')}%0ABudget: ${f.get('budget')}%0AMessage: ${f.get('message')}`; window.open(`https://wa.me/${d.whatsapp}?text=${msg}`, '_blank'); setSent(true) }; return <section className="section enquiry" id="enquire"><div className="enquiry-intro"><motion.div {...reveal}><p className="eyebrow dark">Let’s make it yours <span /></p><h2>Begin your<br /><em>next chapter.</em></h2><p>Tell us a little about what you are looking for, and our advisor will be in touch.</p></motion.div><a className="brochure-link" href={d.brochure} download><FiDownload /> Download project brochure</a></div><motion.form {...reveal} onSubmit={submit}><label>Full name<input required name="name" placeholder="Your name" /></label><label>Mobile number<input required name="mobile" type="tel" placeholder="+91 00000 00000" /></label><label>Email address<input required name="email" type="email" placeholder="you@email.com" /></label><label>Interested in<select name="configuration" defaultValue=""><option value="" disabled>Select configuration</option>{d.plans.map(p => <option key={p.label}>{p.label}</option>)}</select></label><label>Budget<select name="budget" defaultValue=""><option value="" disabled>Select budget</option><option>₹ 75L – ₹ 1Cr</option><option>₹ 1Cr – ₹ 1.5Cr</option><option>₹ 1.5Cr+</option></select></label><label className="full">Message<textarea name="message" rows="3" placeholder="Anything specific you have in mind?" /></label><button className="btn btn-dark full" type="submit">{sent ? 'Thank you — opening WhatsApp' : 'Send enquiry'} <FiArrowUpRight /></button></motion.form></section> }
function Contact() { return <footer className="footer"><div className="footer-main"><div><a href="#home" className="brand brand-footer"><span className="brand-mark">A</span><span>{d.name}</span></a><p className="footer-blurb">A considered collection of homes<br />for the way you want to live.</p></div><div><p className="footer-label">Visit us</p><p>{d.address}</p><a href={`mailto:${d.email}`}>{d.email}</a></div><div><p className="footer-label">Speak with us</p><a href={`tel:${d.phone.replaceAll(' ', '')}`}>{d.phone}</a><a href={`https://wa.me/${d.whatsapp}`}>WhatsApp us</a></div><div><p className="footer-label">Explore</p><a href="#about">About project</a><a href="#amenities">Amenities</a><a href="#plans">Floor plans</a><a href="#location">Location</a></div></div><div className="footer-bottom"><span>© 2026 Aurelia Heights. All rights reserved.</span><span>RERA: P52100000000</span><div className="socials"><a href="#home" aria-label="Instagram"><FiInstagram /></a><a href="#home" aria-label="Facebook"><FiFacebook /></a><a href="#home" aria-label="LinkedIn"><FiLinkedin /></a></div></div></footer> }
function FloatingButtons() { return <><div className="floating"><a className="float-whatsapp" href={`https://wa.me/${d.whatsapp}`} aria-label="WhatsApp"><FiMessageCircle /></a><a className="float-call" href={`tel:${d.phone.replaceAll(' ', '')}`} aria-label="Call"><FiPhone /></a></div><div className="mobile-cta"><a href={`tel:${d.phone.replaceAll(' ', '')}`}><FiPhone /> Call now</a><a href={`https://wa.me/${d.whatsapp}`}><FiMessageCircle /> WhatsApp</a><a href="#enquire">Enquire</a></div></> }
export default function App() { return <><Navbar /><main><Hero /><About /><Highlights /><Amenities /><Plans /><Gallery /><Location /><Enquiry /></main><Contact /><FloatingButtons /></> }
